global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
      
  - job_name: 'auth-mongodb-prometheus-exporter'
    static_configs:
      - targets: [ 'auth-mongodb-prometheus-exporter:9216' ]
 
   - job_name: 'account-mongodb-prometheus-exporter'
    static_configs:
      - targets: [ 'account-mongodb-prometheus-exporter:9216' ]
      
  - job_name: 'statistics-mongodb-prometheus-exporter'
    static_configs:
      - targets: [ 'statistics-mongodb-prometheus-exporter:9216' ]
